version: "3.7"

networks:
  {{cookiecutter.project_name}}:
  traefik-public:
    external: true

volumes:
  {{cookiecutter.project_name}}-media.vol:
  {{cookiecutter.project_name}}-static.vol:
  {{cookiecutter.project_name}}-db-data.vol:


services:
  {{cookiecutter.project_name}}-db:
    image: postgres:15.0
    container_name: {{cookiecutter.project_name}}-db
    restart: always
    tty: true
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - {{cookiecutter.project_name}}-db-data.vol:/var/lib/postgresql/data
    networks:
      - {{cookiecutter.project_name}}

  {{cookiecutter.project_name}}-redis:
    image: redis
    networks:
      - {{cookiecutter.project_name}}


  {{cookiecutter.project_name}}:
    image: reg.bernetco.ir/{{cookiecutter.project_name}}:staging
    sysctls:
      net.core.somaxconn: 1024
    volumes:
      - {{cookiecutter.project_name}}-media.vol:/app/media
      - {{cookiecutter.project_name}}-static.vol:/app/static
    networks:
      - {{cookiecutter.project_name}}
      - traefik-public
    environment:
      - DEBUG=on
      - SERVE_STRATEGY=production
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=psql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@{{cookiecutter.project_name}}-db:5432/${POSTGRES_DB}
      - CACHE_URL=rediscache://redis:6379/1?client_class=django_redis.client.DefaultClient
      - KAVENEGAR_AUTH_TOKEN=${KAVENEGAR_AUTH_TOKEN}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      - REDIS_HOST={{cookiecutter.project_name}}-redis
      - CCREMAILS=${CCREMAILS}
      - ADMINS_MOBILE_NUMBER=${STG_ADMIN_MOBILE_NUMBER}
    labels:
      - "ccr.receivers=${CCREMAILS}"
    depends_on:
      - {{cookiecutter.project_name}}-db
    deploy:
      endpoint_mode: dnsrr
      update_config:
        order: start-first
        monitor: "5m"
      rollback_config:
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.{{cookiecutter.project_name}}-staging.rule=Host(`{{cookiecutter.project_name}}.bernetco.ir`)"
        - "traefik.http.routers.{{cookiecutter.project_name}}-staging.entrypoints=websecure"
        - "traefik.http.routers.{{cookiecutter.project_name}}-staging.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.{{cookiecutter.project_name}}-staging.loadbalancer.server.port=8000"

  {{cookiecutter.project_name}}-celery:
    image: reg.bernetco.ir/{{cookiecutter.project_name}}:staging
    command: celery -A {{cookiecutter.project_name}}.celery worker -l info --pidfile="celeryworker.pid"
    environment:
      - DEBUG=on
      - SECRET_KEY=${SECRET_KEY}
      - SERVE_STRATEGY=production
      - DATABASE_URL=psql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@{{cookiecutter.project_name}}-db:5432/${POSTGRES_DB}
      - CACHE_URL=rediscache://redis:6379/1?client_class=django_redis.client.DefaultClient
      - KAVENEGAR_AUTH_TOKEN=${KAVENEGAR_AUTH_TOKEN}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      - REDIS_HOST={{cookiecutter.project_name}}-redis
      - CCREMAILS=${CCREMAILS}
      - ADMINS_MOBILE_NUMBER=${STG_ADMIN_MOBILE_NUMBER}
    volumes:
      - {{cookiecutter.project_name}}-media.vol:/app/media
      - {{cookiecutter.project_name}}-static.vol:/app/static
    networks:
      - {{cookiecutter.project_name}}
      - traefik-public
    depends_on:
      - {{cookiecutter.project_name}}-db
      - {{cookiecutter.project_name}}-redis

  {{cookiecutter.project_name}}-beat:
    image: reg.bernetco.ir/{{cookiecutter.project_name}}:staging
    command: celery -A {{cookiecutter.project_name}}.celery beat -l info
    environment:
      - DEBUG=on
      - SERVE_STRATEGY=production
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=psql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@{{cookiecutter.project_name}}-db:5432/${POSTGRES_DB}
      - CACHE_URL=rediscache://redis:6379/1?client_class=django_redis.client.DefaultClient
      - KAVENEGAR_AUTH_TOKEN=${KAVENEGAR_AUTH_TOKEN}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      - REDIS_HOST={{cookiecutter.project_name}}-redis
      - CCREMAILS=${CCREMAILS}
      - ADMINS_MOBILE_NUMBER=${STG_ADMIN_MOBILE_NUMBER}

    volumes:
      - {{cookiecutter.project_name}}-media.vol:/app/media
      - {{cookiecutter.project_name}}-static.vol:/app/static
    networks:
      - {{cookiecutter.project_name}}
      - traefik-public
    depends_on:
      - {{cookiecutter.project_name}}-db
      - {{cookiecutter.project_name}}-redis
