[tool.black]
line-length = 120
# By default, `black` will ignore skip configuration when paths are explicitly provided.
# In order for `pre-commit` to respect this configuration, `force-exclude` needs to be explicitly set.
force-exclude = 'migrations'

[tool.isort]
# https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#isort
profile = "black"
# By default, `isort` will ignore skip configuration when paths are explicitly provided.
# In order for `pre-commit` to respect this configuration, `filter_files` needs to be set to true.
# https://jugmac00.github.io/blog/isort-and-pre-commit-a-friendship-with-obstacles/
filter_files = true
skip_glob = ["*/migrations/*", "config/*"]
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

multi_line_output = 5
include_trailing_comma = true
force_grid_wrap = 2
use_parentheses = true
ensure_newline_before_comments = true
combine_as_imports = true